### DISCUSSION TITLE
limiting GPU Memory usage

### DISCUSSION THREAD

**Discussion by varunpan** [exadel-inc/CompreFace#1114] [Q&A] [answered]
Hi,
I am wondering is there is a way to limit gpu memory consumption or add swap memory to handle additional memory needs?

I am running CompreFace in a single container using image: `exadel/compreface:1.0.0-arcface-r100-gpu` image with nvidia Quadro M2200 gpu that has only 4gb of memory. I have added `UWSGI_PROCESSES: 1` and `API_JAVA_OPTS: -Xmx1g` env variables in the compose file to limit memory consumption. However, it is consuming all the available gpu memory.
See my full compose file below:
```
  compreface:
    container_name: CompreFace
    image: exadel/compreface:1.0.0-arcface-r100-gpu
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - compreface-db:/var/lib/postgresql/data
    environment:
      - UWSGI_PROCESSES=1
      - API_JAVA_OPTS=-Xmx1g
    ports:
      - 8000:80
```
