### ISSUE TITLE
Unable to open Application

### ISSUE THREAD

**Issue by nimeshgarg** [exadel-inc/CompreFace#1036]
The following error shows open trying to open application

<html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx</center> </body> </html>      

1. Go to https://compreface-ytwodnusoa-em.a.run.app/
2. Create user/Login 
3. Error message show whenever any application is tried to open

**Screenshots**

![image](https://user-images.githubusercontent.com/51132740/222038064-c99071cf-ece1-4ad0-b104-11c5081f742f.png)

**Comment by pospielov** [comment]
Could you run those commands and attach the result to the ticket?
`docker ps`
`docker-compose logs`

**Comment by kigorw** [comment]
Similar issue
compreface-ui             | 2023/04/13 09:54:32 [error] 64#64: *81 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: ui, request: "GET /api/v1/consistence/status HTTP/1.1", upstream: "http://172.18.0.4:8080/api/v1/consistence/status", host: "127.0.0.1:8000", referrer: "http://127.0.0.1:8000/application?app=00000000-0000-0000-0000-000000000001"

**Comment by pospielov** [comment]
@kigorw, I can't understand the problem from your log
Could you run those commands and attach the result to the ticket?
`docker ps`
`docker-compose logs`

**Comment by marq24** [comment]
I just run into the same issue - in my case I am are running my postgres on a different port (in the .env) - so in order to solve my issue I need to insert an appropriate port mapping into my docker-compose.yml (remove the old containers) after you altered the compose file...

```
  compreface-postgres-db:
    image: ${registry}compreface-postgres-db:${POSTGRES_VERSION}
    restart: unless-stopped
    container_name: "compreface-postgres-db"
    ports:
      - ${postgres_port}:5432
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgres_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data
```
