### ISSUE TITLE
Update docker-compose.yml of GPU enabled builds so they also work on Docker Desktop Windows

### ISSUE THREAD

**Issue by calloatti** [exadel-inc/CompreFace#1103]
**Is your feature request related to a problem? Please describe.**

Current use of `runtime: nvidia` in the `compreface-core:` service of  ` docker-compose.yml` for GPU enabled builds means that they will not work on Docker Desktop Windows (At least I have not being able to find a solution on how to install the Nvidia runtime on Windows)

**Describe the solution you'd like**
Switch to enabling GPU access using the "device" structure as detailed in https://docs.docker.com/compose/gpu-support/ This works on Windows and I presume it also works on Docker Linux

**Additional context**
See: https://github.com/exadel-inc/CompreFace/discussions/1084#discussioncomment-6408348 for proof that this works

Example:

```
  compreface-core:
    image: ${registry}compreface-core:${CORE_VERSION}
    restart: always
    container_name: "compreface-core"
    environment:
      - ML_PORT=3000
      - UWSGI_PROCESSES=${uwsgi_processes:-2}
      - UWSGI_THREADS=${uwsgi_threads:-1}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
