### ISSUE TITLE
[BUG] Nvidia in Docker: MobilenetGPU/ - uWSGI died - How to debug?

### ISSUE THREAD

**Issue by ozett** [exadel-inc/CompreFace#652]
**Describe the bug**
detection hangs, because of processes killed. the log scrolls up with some backtraces i cannot read

**To Reproduce**
starting docker-compose
going to webgui
testing facerec, but it doesnt run

**Expected behavior**
running compreface gpu models with compreface-core in docker without error

**Screenshots**
![image](https://user-images.githubusercontent.com/5937811/139917614-cfc12b41-5de4-4590-85ac-13f2c2f5fc7d.png)

**Desktop (please complete the following information):**
 - Nvidia Gforce 
 - ubuntu 20.04.LTS
 - Cuda ver 11.4
```
processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz


root@ub20-frigate4:/usr/src# nvidia-smi -L
GPU 0: NVIDIA GeForce GTX 1660 (UUID: GPU-65d82c7a-fb69-3e25-a081-2baef57fba23)
root@ub20-frigate4:/usr/src#

```

**Additional context**

.env:
```
root@ub20-frigate4:/usr/src# cat .env
registry=exadel/
postgres_username=postgres
postgres_password=postgres
postgres_db=frs
postgres_domain=compreface-postgres-db
postgres_port=5432
email_host=smtp.gmail.com
email_username=
email_from=
email_password=
enable_email_server=false
save_images_to_db=true
compreface_api_java_options=-Xmx8g
compreface_admin_java_options=-Xmx8g
ADMIN_VERSION=0.6.1
API_VERSION=0.6.1
FE_VERSION=0.6.1
CORE_VERSION=0.6.1-mobilenet-gpu
root@ub20-frigate4:/usr/src#
```

docker-compose.yml:
```
root@ub20-frigate4:/usr/src# cat dc-cface.yml
version: '3.4'

volumes:
  postgres-data:

services:
  compreface-postgres-db:
    image: postgres:11.5
    container_name: "compreface-postgres-db"
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgres_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  compreface-admin:
    image: ${registry}compreface-admin:${ADMIN_VERSION}
    container_name: "compreface-admin"
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_URL=jdbc:postgresql://${postgres_domain}:${postgres_port}/${postgres_db}
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_EMAIL_SERVER=${enable_email_server}
      - EMAIL_HOST=${email_host}
      - EMAIL_USERNAME=${email_username}
      - EMAIL_FROM=${email_from}
      - EMAIL_PASSWORD=${email_password}
      - ADMIN_JAVA_OPTS=${compreface_admin_java_options}
    depends_on:
      - compreface-postgres-db
      - compreface-api

  compreface-api:
    image: ${registry}compreface-api:${API_VERSION}
    container_name: "compreface-api"
    depends_on:
      - compreface-postgres-db
    environment:
      - POSTGRES_USER=${postgres_username}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_URL=jdbc:postgresql://${postgres_domain}:${postgres_port}/${postgres_db}
      - SPRING_PROFILES_ACTIVE=dev
      - API_JAVA_OPTS=${compreface_api_java_options}
      - SAVE_IMAGES_TO_DB=${save_images_to_db}

  compreface-fe:
    image: ${registry}compreface-fe:${FE_VERSION}
    container_name: "compreface-ui"
    ports:
      - "8000:80"
    depends_on:
      - compreface-api
      - compreface-admin

  compreface-core:
    image: ${registry}compreface-core:${CORE_VERSION}
    container_name: "compreface-core"
    runtime: nvidia
    environment:
      - ML_PORT=3000
root@ub20-frigate4:/usr/src#```




dont know whats needed, dont know how to get more debug-outout. but i will do to help..
```
compreface-core           | [17:37:48] src/engine/engine.cc:55: MXNet start using engine: ThreadedEnginePerDevice
compreface-core           | !!! uWSGI process 78 got Segmentation Fault !!!
compreface-core           | *** backtrace of 78 ***
compreface-core           | uwsgi(uwsgi_backtrace+0x2a) [0x55e0d380c33a]
compreface-core           | uwsgi(uwsgi_segfault+0x23) [0x55e0d380c723]
compreface-core           | /lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7f6c3c736040]
```
