### ISSUE TITLE
How to use more GPUs when starting container?

### ISSUE THREAD

**Issue by Chernobyl81** [exadel-inc/CompreFace#746]
I have a host that contains two tesla T4 GPUs(15GB RAM per GPU), and setup uwsgi.ini in compreface-core container with processes=10 . When I start containers for load testing, I found the uwsgi only uses one GPU. How can I setup or rebuild image? Thanks!

**Comment by pospielov** [comment]
We didn't try to run CompreFace with several GPUs.
Here are my thoughts:
Option 1. 
https://github.com/exadel-inc/CompreFace/blob/199875f1841af8ea9b78d7cf941e96f37a5336c3/embedding-calculator/src/services/facescan/plugins/insightface/insightface.py#L207
Here you can see how we define mxnet context and then init Module:
`ctx = mx.gpu(self._CTX_ID) if self._CTX_ID >= 0 else mx.cpu()`
`model = mx.mod.Module(symbol=sym, context=ctx, label_names=None)`
And here is the example from official documentation how to use mxnet with several GPU:
`module = mx.module.Module(context=[mx.gpu(0), mx.gpu(2)], ...)`
So you can change our code to:
`ctx = [mx.gpu(0), mx.gpu(1)]`
`model = mx.mod.Module(symbol=sym, context=ctx, label_names=None)`
and rebuild CompreFace

Option 2.
We use the environment variable GPU_IDX to define the GPU index. In one instance you can use only one GPU.
But you can run two instances of `compreface-core`  and add different values in each instance. 
e.g. you can change your docker-compose:
```
  compreface-core1:
    restart: always
    image: ${registry}compreface-core:${CORE_VERSION}
    restart: always
    container_name: "compreface-core"
    environment:
      - ML_PORT=3000
      - GPU_IDX=0
   
  compreface-core2:
    restart: always
    image: ${registry}compreface-core:${CORE_VERSION}
    restart: always
    container_name: "compreface-core"
    environment:
      - ML_PORT=3000
      - GPU_IDX=1
```
In this case, you won't need to change code and rebuild CompreFace.
